
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abdun/config-server.git
  user:
    name: anoor@mail.com
    password: Planet#0626
management:
  endpoints:
    web:
      exposure:
        include: '*'